apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-code-challenge-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-code-challenge-fe
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-code-challenge-fe
    spec:
      containers:
      - name: gke-code-challenge-fe
        image: us-east1-docker.pkg.dev/codechallenge-349907/char/code-challenge-image-fe:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m